# Site settings
title: A public journal of webdev discoveries
description: A public journal of webdev discoveries
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://moseym.github.io/"
permalink: /:year/:month/:day/:title.html

# User settings
username: Moseyee
user_description: I am self-characterized as unconventional (in theory). I am a fullstack developer who enjoys doing a variety of things. I wanted to start documenting my findings, some quick tricks that I have learned along the way and the likes. So why not with a Jekyll blog. You should expect clean, bloat-free, lightly comedic posts (or possibly have no expectations, makes it more interesting)
user_title: Web Developer
twitter_username: regalcoder
github_username: moseym
linkedin_username: margaretmoseyee

# Google-analytics
# google-analytics:
#   id: "UA-104303368-1"

exclude: ['package.json', 'src' , 'node_modules']
